---
id: "iClass"
parent_id: "Interfaces section"
type: mixin
line_number: 7
description: |
  Interface des classes Javalyss.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php

---
id: "iClass.Initialize"
parent_id: "iClass"
type: class method
line_number: 13
description: |
  Cette méthode initialise les événements de la classe.

signatures:
 -
  signature: "iClass.Initialize()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php

---
id: "iClass#commit"
parent_id: "iClass"
type: instance method
line_number: 19
description: |
  Cette méthode enregistre les informations de la classe en base de données.

signatures:
 -
  signature: "iClass#commit()"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php

---
id: "iClass#delete"
parent_id: "iClass"
type: instance method
line_number: 25
description: |
  Cette méthode supprime les informations de la classe de la base de données.

signatures:
 -
  signature: "iClass#delete()"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php

---
id: "iClass.exec"
parent_id: "iClass"
type: class method
line_number: 33
description: |
  Cette méthode exécute une commande `op` et affiche un résultat au format JSON de préférence.
  La méthode peut retourner 0 ou une chaine de caractère pour indiquer une erreur lors de l'exécution d'une commande.

signatures:
 -
  signature: "iClass.exec(op)"
  return_value: "Boolean"
arguments:
 -
  name: op
  types: [String]
  description: >
    Nom de la commande à exécuter.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php

---
id: "iClass.GetList"
parent_id: "iClass"
type: class method
line_number: 42
description: |
  Cette méthode liste l'ensemble des données gérées par la classe.

signatures:
 -
  signature: "iClass.GetList([clauses [, options]])"
  return_value: "Array | Boolean"
arguments:
 -
  name: clauses
  types: [Object]
  description: >
    Objet de restriction de la liste.

 -
  name: options
  types: [Object]
  description: >
    Objet de configuration de la liste.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php

---
id: "iClass.onGetList"
parent_id: "iClass"
type: class method
line_number: 51
description: |
  Cette méthode est appelée par un objet [[Request]] lors de son exécution.

signatures:
 -
  signature: "iClass.onGetList(row [,request])"
  return_value: "void"
arguments:
 -
  name: row
  types: [Array]
  description: >
    Ligne traité par la requête.

 -
  name: request
  types: [Request]
  description: >
    Requêt en cours d'exécution.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iclass.php