---
id: "iPlugin"
parent_id: "Interfaces section"
type: mixin
line_number: 7
description: |
  Interface des classes gérant une extension Javalyss.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iplugin.php

---
id: "iPlugin.Initialize"
parent_id: "iPlugin"
type: class method
line_number: 13
description: |
  Cette méthode initialise les événements de la classe.

signatures:
 -
  signature: "iPlugin.Initialize()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iplugin.php

---
id: "iPlugin.Install"
parent_id: "iPlugin"
type: class method
line_number: 18
description: |
  Cette méthode installe l'extension ou une partie de l'extension gérées par la classe.

signatures:
 -
  signature: "iPlugin.Install()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iplugin.php

---
id: "iPlugin.Uninstall"
parent_id: "iPlugin"
type: class method
line_number: 25
description: |
  Cette méthode désintalle  l'extension et supprime les données liées à l'extension si `eraseData` est vrai.

signatures:
 -
  signature: "iPlugin.Uninstall(eraseData)"
  return_value: "void"
arguments:
 -
  name: eraseData
  types: [Boolean]
  description: >
    Suppression de données.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iplugin.php

---
id: "iPlugin.exec"
parent_id: "iPlugin"
type: class method
line_number: 33
description: |
  Cette méthode exécute une commande `op` et affiche un résultat au format JSON de préférence.
  La méthode peut retourner 0 ou une chaine de caractère pour indiquer une erreur lors de l'exécution d'une commande.

signatures:
 -
  signature: "iPlugin.exec(op)"
  return_value: "Boolean"
arguments:
 -
  name: op
  types: [String]
  description: >
    Nom de la commande à exécuter.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iplugin.php

---
id: "iPlugin.execSafe"
parent_id: "iPlugin"
type: class method
line_number: 41
description: |
  Cette méthode exécute une commande - en mode non connecté - et affiche un résultat au format JSON de préférence.
  La méthode peut retourner 0 ou une chaine de caractère pour indiquer une erreur lors de l'exécution d'une commande.

signatures:
 -
  signature: "iPlugin.execSafe(op)"
  return_value: "Boolean"
arguments:
 -
  name: op
  types: [String]
  description: >
    Nom de la commande à exécuter.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/interface/iplugin.php