---
id: "CoreUI"
parent_id: "Core section"
type: mixin
included: ["BaseUI"]
line_number: 20
description: |
  Cette classe gère l'initialisation des actions de base du logiciel dont :
  
  * L'interception des requêtes AJAX,
  * La compilation de CSS,
  * Le lancement de la page du planning,
  * Le lancement de BlogPress.
  
  #### Informations
  
  * Auteur : Lenzotti Romain | ANALEMME
  * Fichier : abstract_coreui.php
  * Note :	This work is licensed under a Creative Commons Attribution 2.5 Generic License http://creativecommons.org/licenses/by/2.5/

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Uri"
parent_id: "CoreUI"
type: class property
line_number: 28
description: |


signatures:
 -
  signature: "CoreUI.Uri"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Name"
parent_id: "CoreUI"
type: class property
line_number: 32
description: |


signatures:
 -
  signature: "CoreUI.Name"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.ScriptLink"
parent_id: "CoreUI"
type: class property
line_number: 36
description: |


signatures:
 -
  signature: "CoreUI.ScriptLink"
  return_value: "Array"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Script"
parent_id: "CoreUI"
type: class property
line_number: 57
description: |


signatures:
 -
  signature: "CoreUI.Script"
  return_value: "Array"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Css"
parent_id: "CoreUI"
type: class property
line_number: 61
description: |


signatures:
 -
  signature: "CoreUI.Css"
  return_value: "Array"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Create"
parent_id: "CoreUI"
type: class method
line_number: 67
description: |
  Cette méthode créée la page du planning.

signatures:
 -
  signature: "CoreUI.Create()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Header"
parent_id: "CoreUI"
type: class method
line_number: 101
description: |
  Cette méthode créee l'entête du Blog.
  fires planning:header
  
  Cette méthode construit l'entête de la page.

signatures:
 -
  signature: "CoreUI.Header()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.EnqueueScript"
parent_id: "CoreUI"
type: class method
line_number: 120
description: |
  Cette méthode gère l'inclusion sans doublon des script Javascript vers le template.

signatures:
 -
  signature: "CoreUI.EnqueueScript(scriptname [, src [, parameters]])"
  return_value: "void"
arguments:
 -
  name: scriptname
  types: [String]
  description: >
    Nom du script tel que `jquery`, `prototype` etc...

 -
  name: src
  types: [String]
  description: >
    Lien du script à charger

 -
  name: parameters
  types: [String]
  description: >
    Paramètre à passer au script JS.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.ImportCSS"
parent_id: "CoreUI"
type: class method
line_number: 143
description: |
  Cette méthode permet d'importer un script CSS en vue d'être inséré dans l'entête du template.

signatures:
 -
  signature: "CoreUI.ImportCSS(src, media)"
  return_value: "void"
arguments:
 -
  name: src
  types: [String]
  description: >
    Lien du script css à importer.

 -
  name: media
  types: [String]
  description: >
    Média cible du script css.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.ImportCompilableCSS"
parent_id: "CoreUI"
type: class method
line_number: 152
description: |
  Cette méthode permet d'importer un script CSS qui devra être compilé et compressé avant d'être affiché dans l'entête du template.

signatures:
 -
  signature: "CoreUI.ImportCompilableCSS(link)"
  return_value: "void"
arguments:
 -
  name: link
  types: [String]
  description: >
    Lien du script css à importer.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.CompileCSS"
parent_id: "CoreUI"
type: class method
line_number: 160
description: |
  Cette méthode compile et compresse les fichiers CSS en fonction des paramètres du template.

signatures:
 -
  signature: "CoreUI.CompileCSS()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.ImportTemplate"
parent_id: "CoreUI"
type: class method
line_number: 268
description: |
  Cette méthode permet d'importer un script CSS en vue d'être inséré dans l'entête du template.

signatures:
 -
  signature: "CoreUI.ImportTemplate(src, media)"
  return_value: "void"
arguments:
 -
  name: src
  types: [String]
  description: >
    Lien du script css à importer.

 -
  name: media
  types: [String]
  description: >
    Média cible du script css.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.Draw"
parent_id: "CoreUI"
type: class method
line_number: 287
description: |
  Cette méthode génére la page du planning.

signatures:
 -
  signature: "CoreUI.Draw()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.StartInterface"
parent_id: "CoreUI"
type: class method
line_number: 327
description: |
  Cette méthode lance le logiciel ainsi que les procédures suivantes :
  
  * Analyse de la requête AJAX si elle existe.
  * Vérifie si la page demandée est bien celle du planning.
  * Vérifie si la page demandée est un script de CSS.
  * Vérifie si le logiciel à une MAJ en attente de configuration.
  * Importe les extensions du logiciel.
  * Donne la main aux extensions si aucune des procédures précédentes n'a intérrompue le lancement du logiciel.

signatures:
 -
  signature: "CoreUI.StartInterface()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php

---
id: "CoreUI.StartAdmin"
parent_id: "CoreUI"
type: class method
line_number: 398
description: |
  Cette méthode lance l'interface d'administration.

signatures:
 -
  signature: "CoreUI.StartAdmin()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_coreui.php