---
id: "BaseUI"
parent_id: "Core section"
type: mixin
line_number: 16
description: |
  Cette classe l'intégration des librairies JS et CSS dans les templates.
  
  #### Informations
  
  * Auteur : Lenzotti Romain | ANALEMME
  * Fichier : abstract_baseui.php
  * Note :	This work is licensed under a Creative Commons Attribution 2.5 Generic License http://creativecommons.org/licenses/by/2.5/

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.ScriptLink"
parent_id: "BaseUI"
type: class property
line_number: 22
description: |
  Liste des listes liens des librairies JavaScript.

signatures:
 -
  signature: "BaseUI.ScriptLink"
  return_value: "Array"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.Lang"
parent_id: "BaseUI"
type: class property
line_number: 52
description: |
  Langue à utiliser pour l'interface.

signatures:
 -
  signature: "BaseUI.Lang"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.Header"
parent_id: "BaseUI"
type: class property
line_number: 56
description: |


signatures:
 -
  signature: "BaseUI.Header"
  return_value: "Header"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.Body"
parent_id: "BaseUI"
type: class property
line_number: 60
description: |


signatures:
 -
  signature: "BaseUI.Body"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.Theme"
parent_id: "BaseUI"
type: class property
line_number: 64
description: |


signatures:
 -
  signature: "BaseUI.Theme"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.Title"
parent_id: "BaseUI"
type: class property
line_number: 68
description: |


signatures:
 -
  signature: "BaseUI.Title"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.Resolve"
parent_id: "BaseUI"
type: class method
line_number: 75
description: |
  - link(String): Lien du script à résoudre.
  
  Cette méthode tente de résoudre le chemin d'un lien codé.

signatures:
 -
  signature: "BaseUI.Resolve(link)"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.GetTemplateName"
parent_id: "BaseUI"
type: class method
line_number: 83
description: |
  Cette méthode retourne le nom du template WindowJS à charger.

signatures:
 -
  signature: "BaseUI.GetTemplateName()"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.DrawStdLib"
parent_id: "BaseUI"
type: class method
line_number: 103
description: |
  Cette méthode charge les librairies standards javascript dans la page cible.

signatures:
 -
  signature: "BaseUI.DrawStdLib(lib)"
  return_value: "String"
arguments:
 -
  name: lib
  types: [String]
  description: >
    Nom de la libraire.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php

---
id: "BaseUI.DrawParameters"
parent_id: "BaseUI"
type: class method
line_number: 256
description: |
  Cette méthode écrit les paramètres JS nécéssaire à l'initialisation d'une page.

signatures:
 -
  signature: "BaseUI.DrawParameters()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/abstract_baseui.php