---
id: "SystemCache"
parent_id: "Core section"
type: class
included: ["ObjectTools"]
line_number: 15
description: |
  Cette utilitaire gère la mise en cache de fichier.
  
  #### Informations
  
  * Auteur : Lenzotti Romain
  * Fichier : class_system_cache.php
  * Note :	This work is licensed under a Creative Commons Attribution 2.5 Generic License http://creativecommons.org/licenses/by/2.5/

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache#Width"
parent_id: "SystemCache"
type: instance property
line_number: 19
description: |


signatures:
 -
  signature: "SystemCache#Width"
  return_value: "Number"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache#Width"
parent_id: "SystemCache"
type: instance property
line_number: 23
description: |


signatures:
 -
  signature: "SystemCache#Width"
  return_value: "Number"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache#ID"
parent_id: "SystemCache"
type: instance property
line_number: 27
description: |


signatures:
 -
  signature: "SystemCache#ID"
  return_value: "Number"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache#Src"
parent_id: "SystemCache"
type: instance property
line_number: 34
description: |
  Lien du fichier source.

signatures:
 -
  signature: "SystemCache#Src"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache#SrcCache"
parent_id: "SystemCache"
type: instance property
line_number: 39
description: |
  Lien du fichier source dans le cache.

signatures:
 -
  signature: "SystemCache#SrcCache"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "new SystemCache"
parent_id: "SystemCache"
type: constructor
line_number: 48
description: |
  Cette méthode créée une nouvelle instance [[SystemCache]] permettant d'ajouter ou de supprimer un fichier du cache.

signatures:
 -
  signature: "new SystemCache()"
 -
  signature: "new SystemCache(object)"
 -
  signature: "new SystemCache(array)"
 -
  signature: "new SystemCache(fileSrc)"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache.Push"
parent_id: "SystemCache"
type: class method
line_number: 73
description: |
  Cette méthode ajoute un fichier au gestionnaire du cache.

signatures:
 -
  signature: "SystemCache.Push(fileSrc)"
  return_value: "String"
 -
  signature: "SystemCache.Push(object)"
  return_value: "String"
 -
  signature: "SystemCache.Push(array)"
  return_value: "String"
 -
  signature: "SystemCache.Push(systemCache)"
  return_value: "String"
arguments:
 -
  name: fileSrc
  types: [String]
  description: >
    Lien du fichier à mettre en cache.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php

---
id: "SystemCache.Remove"
parent_id: "SystemCache"
type: class method
line_number: 109
description: |
  Cette méthode supprime un fichier du gestionnaire du cache.

signatures:
 -
  signature: "SystemCache.Remove(fileSrc)"
  return_value: "void"
 -
  signature: "SystemCache.Remove(object)"
  return_value: "void"
 -
  signature: "SystemCache.Remove(array)"
  return_value: "void"
 -
  signature: "SystemCache.Remove(systemCache)"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_cache.php