---
id: "Plugin"
parent_id: "Core section"
type: class
included: ["ObjectTools"]
line_number: 7
description: |
  Cette classe gère les extensions du logiciel.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.TABLE_NAME"
parent_id: "Plugin"
type: class property
line_number: 17
description: |
  Nom de la table gérée par la classe.

signatures:
 -
  signature: "Plugin.TABLE_NAME"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.PRIMARY_KEY"
parent_id: "Plugin"
type: class property
line_number: 22
description: |
  Clef primaire de la table Plugin.TABLE_NAME gérée par la classe.

signatures:
 -
  signature: "Plugin.PRIMARY_KEY"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Folder"
parent_id: "Plugin"
type: instance property
line_number: 29
description: |
  Dossier relatif de l'extension

signatures:
 -
  signature: "Plugin#Folder"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Name"
parent_id: "Plugin"
type: instance property
line_number: 34
description: |
  Nom de l'extension

signatures:
 -
  signature: "Plugin#Name"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Author"
parent_id: "Plugin"
type: instance property
line_number: 39
description: |
  Nom de l'auteur de l'extension

signatures:
 -
  signature: "Plugin#Author"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#URI"
parent_id: "Plugin"
type: instance property
line_number: 44
description: |
  Adresse web de l'extension

signatures:
 -
  signature: "Plugin#URI"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Author_URI"
parent_id: "Plugin"
type: instance property
line_number: 49
description: |
  Adresse du site web de l'auteur

signatures:
 -
  signature: "Plugin#Author_URI"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Version"
parent_id: "Plugin"
type: instance property
line_number: 54
description: |
  Version de l'extension

signatures:
 -
  signature: "Plugin#Version"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Description"
parent_id: "Plugin"
type: instance property
line_number: 59
description: |
  Description de l'extension

signatures:
 -
  signature: "Plugin#Description"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#Active"
parent_id: "Plugin"
type: instance property
line_number: 64
description: |
  Etat de l'extension

signatures:
 -
  signature: "Plugin#Active"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "new Plugin"
parent_id: "Plugin"
type: constructor
line_number: 81
description: |
  Cette méthode créée une nouvelle instance de [[Plugin]].

signatures:
 -
  signature: "new Plugin()"
 -
  signature: "new Plugin(json)"
 -
  signature: "new Plugin(array)"
 -
  signature: "new Plugin(obj)"
 -
  signature: "new Plugin(pluginid)"
arguments:
 -
  name: json
  types: [String]
  description: >
    Chaine de caractères JSON équivalente à une instance [[Plugin]].

 -
  name: array
  types: [Array]
  description: >
    Tableau associatif équivalent à une instance [[Plugin]].

 -
  name: obj
  types: [Object]
  description: >
    Objet équivalent à une instance [[Plugin]].

 -
  name: pluginid
  types: [int]
  description: >
    Numéro d'identifiant d'une extension. Les informations de l'extension seront récupérées depuis la base de données.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.Initialize"
parent_id: "Plugin"
type: class method
line_number: 97
description: |
  Cette méthode initialise le gestionnaire des extensions.

signatures:
 -
  signature: "Plugin.Initialize()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.Get"
parent_id: "Plugin"
type: class method
line_number: 109
description: |
  Cette méthode retourne le gestion des extensions.

signatures:
 -
  signature: "Plugin.Get()"
  return_value: "PluginManager"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.Import"
parent_id: "Plugin"
type: class method
line_number: 117
description: |
  Cette méthode importe les extensions dans le logiciel.

signatures:
 -
  signature: "Plugin.Import()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.ByName"
parent_id: "Plugin"
type: class method
line_number: 176
description: |
  Cette méthode récupère une extension à partir de son nom.

signatures:
 -
  signature: "Plugin.ByName(name)"
  return_value: "Plugin"
arguments:
 -
  name: name
  types: [String]
  description: >
    Nom de l'extension

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.Uri"
parent_id: "Plugin"
type: class method
line_number: 203
description: |
  Cette méthode retourne l'adresse URI du dossier de l'extension.

signatures:
 -
  signature: "Plugin.Uri()"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.Path"
parent_id: "Plugin"
type: class method
line_number: 211
description: |
  Cette méthode retourne l'adresse absolue du dossier de l'extension.

signatures:
 -
  signature: "Plugin.Path()"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#folder"
parent_id: "Plugin"
type: instance method
line_number: 219
description: |
  Cette méthode retourne le chemin du répertoire de l'extension.

signatures:
 -
  signature: "Plugin#folder()"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#baseName"
parent_id: "Plugin"
type: instance method
line_number: 229
description: |
  Cette méthode retourne le nom de répertoire de l'extension.

signatures:
 -
  signature: "Plugin#baseName()"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#enable"
parent_id: "Plugin"
type: instance method
line_number: 237
description: |
  Cette méthode active l'extension.

signatures:
 -
  signature: "Plugin#enable()"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#disable"
parent_id: "Plugin"
type: instance method
line_number: 272
description: |
  Cette méthode désactive l'extension.

signatures:
 -
  signature: "Plugin#disable([erase])"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin#remove"
parent_id: "Plugin"
type: instance method
line_number: 314
description: |
  Cette méthode supprime le répertoire de l'extension.

signatures:
 -
  signature: "Plugin#remove([erase])"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.exec"
parent_id: "Plugin"
type: class method
line_number: 346
description: |
  Cette méthode exécute une commande `op` et affiche un résultat au format JSON de préférence.
  La méthode peut retourner 0 ou une chaine de caractère pour indiquer une erreur lors de l'exécution d'une commande.

signatures:
 -
  signature: "Plugin.exec(op)"
  return_value: "Boolean"
arguments:
 -
  name: op
  types: [String]
  description: >
    Nom de la commande à exécuter.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.Configure"
parent_id: "Plugin"
type: class method
line_number: 446
description: |
  Cette méthode configure la liste des extensions.

signatures:
 -
  signature: "Plugin.Configure()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.GetList"
parent_id: "Plugin"
type: class method
line_number: 480
description: |
  Cette méthode liste l'ensemble des données gérées par la classe.

signatures:
 -
  signature: "Plugin.GetList([clauses [, options]])"
  return_value: "Array | Boolean"
arguments:
 -
  name: clauses
  types: [Object]
  description: >
    Objet de restriction de la liste.

 -
  name: options
  types: [Object]
  description: >
    Objet de configuration de la liste.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php

---
id: "Plugin.HaveAccess"
parent_id: "Plugin"
type: class method
line_number: 542
description: |
  Cette méthode indique si l'application est accessible pour l'utilisateur connecté.

signatures:
 -
  signature: "Plugin.HaveAccess(appName)"
  return_value: "Boolean"
arguments:
 -
  name: appName
  types: [String]
  description: >
    Nom de l'application.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_plugin.php