---
id: "Role"
parent_id: "Core section"
type: class
included: ["ObjectTools", "iClass"]
line_number: 15
description: |
  Cette classe gère les informations d'un rôle du [[System]].
  
  #### Informations
  
  * Auteur : Lenzotti Romain
  * Fichier : class_role.php
  * Note :	This work is licensed under a Creative Commons Attribution 2.5 Generic License http://creativecommons.org/licenses/by/2.5/

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role.TABLE_NAME"
parent_id: "Role"
type: class property
line_number: 23
description: |
  Nom de la table gérée par la classe.

signatures:
 -
  signature: "Role.TABLE_NAME"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role.PRIMARY_KEY"
parent_id: "Role"
type: class property
line_number: 28
description: |
  Clef primaire de la table Role.TABLE_NAME gérée par la classe.

signatures:
 -
  signature: "Role.PRIMARY_KEY"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#Role_ID"
parent_id: "Role"
type: instance property
line_number: 33
description: |
  Numéro d'identifiant du rôle.

signatures:
 -
  signature: "Role#Role_ID"
  return_value: "int"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#Parent_ID"
parent_id: "Role"
type: instance property
line_number: 38
description: |
  Numéro d'identifiant du rôle parent.

signatures:
 -
  signature: "Role#Parent_ID"
  return_value: "int"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#Name"
parent_id: "Role"
type: instance property
line_number: 43
description: |
  Titre du rôle.

signatures:
 -
  signature: "Role#Name"
  return_value: "int"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#Description"
parent_id: "Role"
type: instance property
line_number: 48
description: |
  Description du rôle

signatures:
 -
  signature: "Role#Description"
  return_value: "int"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#Is_Active"
parent_id: "Role"
type: instance property
line_number: 53
description: |
  Indique que le groupe d'utilisateur peut accèder à l'administration ou pas.

signatures:
 -
  signature: "Role#Is_Active"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "new Role"
parent_id: "Role"
type: constructor
line_number: 72
description: |
  Cette méthode créée une nouvelle instance de [[Role]].

signatures:
 -
  signature: "new Role()"
 -
  signature: "new Role(json)"
 -
  signature: "new Role(array)"
 -
  signature: "new Role(obj)"
 -
  signature: "new Role(roleid)"
arguments:
 -
  name: json
  types: [String]
  description: >
    Chaine de caractères JSON équivalente à une instance [[Role]].

 -
  name: array
  types: [Array]
  description: >
    Tableau associatif équivalent à une instance [[Role]].

 -
  name: obj
  types: [Object]
  description: >
    Objet équivalent à une instance [[Role]].

 -
  name: roleid
  types: [int]
  description: >
    Numéro d'identifiant d'un rôle. Les informations du rôle seront récupérées depuis la base de données.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role.exec"
parent_id: "Role"
type: class method
line_number: 127
description: |
  Cette méthode exécute une commande `op` et affiche un résultat au format JSON de préférence.
  La méthode peut retourner 0 ou une chaine de caractère pour indiquer une erreur lors de l'exécution d'une commande.
  
  #### Liste des commandes gérées par cette méthode
  
  Les commandes suivantes doivent avoir un objet [[Role]] au format `JSON` dans `$_POST['Role']`.
  
  * `role.commit`: Enregistre les informations de l'instance en base de données.
  
  Les commandes suivantes utilisent des champs spécifiques :
  
  * `role.list` :  Liste les utilisateurs en fonction des objets contenus dans `$_POST['clauses']` et `$_POST['options']`.

signatures:
 -
  signature: "Role.exec(op)"
  return_value: "int"
arguments:
 -
  name: op
  types: [String]
  description: >
    Nom de la commande à exécuter.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#commit"
parent_id: "Role"
type: instance method
line_number: 178
description: |
  Cette méthode enregistre les informations de la classe en base de données.

signatures:
 -
  signature: "Role#commit()"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#exists"
parent_id: "Role"
type: instance method
line_number: 238
description: |
  Cette méthode indique si le nom du rôle est déjà attribué.

signatures:
 -
  signature: "Role#exists()"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role.ByName"
parent_id: "Role"
type: class method
line_number: 249
description: |
  Cette méthode retourne un groupe à partir de son nom. Si le groupe n'existe pas, il sera automatiquement créé.

signatures:
 -
  signature: "Role.ByName(name [, parentid = 3 [, enable = false]])"
  return_value: "Role"
arguments:
 -
  name: name
  types: [String]
  description: >
    Nom du rôle.

 -
  name: parentid
  types: [Number]
  description: >
    Role parent si le role n'existe pas.

 -
  name: enable
  types: [Boolean]
  description: >
    Indique si le groupe doit être activé lors de sa création.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role.GetList"
parent_id: "Role"
type: class method
line_number: 287
description: |
  Cette méthode liste l'ensemble des données gérées par la classe.

signatures:
 -
  signature: "Role.GetList([clauses [, options]])"
  return_value: "Array | Boolean"
arguments:
 -
  name: clauses
  types: [Object]
  description: >
    Objet de restriction de la liste.

 -
  name: options
  types: [Object]
  description: >
    Objet de configuration de la liste.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role.onGetList"
parent_id: "Role"
type: class method
line_number: 334
description: |
  Cette méthode est appelée par un objet Requete lors de son exécution.

signatures:
 -
  signature: "Role.onGetList(row [,request])"
  return_value: "void"
arguments:
 -
  name: row
  types: [Array]
  description: >
    Ligne traité par la requête.

 -
  name: request
  types: [Request]
  description: >
    Requêt en cours d'exécution.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#getMeta"
parent_id: "Role"
type: instance method
line_number: 377
description: |
  Cette méthode permet de récuperer une information stockée en base de données dans le champ `Meta`.

signatures:
 -
  signature: "Role#getMeta(key)"
  return_value: "String | int"
arguments:
 -
  name: key
  types: [String]
  description: >
    Nom de la clef.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php

---
id: "Role#setMeta"
parent_id: "Role"
type: instance method
line_number: 390
description: |
  - key (String): clef de la valeur à stocker.
  - value (String | int): Valeur à stocker.
  - obj (Object):
  
  Cette méthode permet d'assigner une information stockée en base de données dans le champ `Meta`.

signatures:
 -
  signature: "Role#setMeta(key, value)"
  return_value: "Boolean"
 -
  signature: "Role#setMeta(obj)"
  return_value: "Boolean"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_role.php