---
id: "SystemTemplate"
parent_id: "Core section"
type: class
line_number: 16
description: |
  Cette classe permet de récupérer les templates du logiciel dans le dossier cible.
  
  #### Informations
  
  * Auteur : Lenzotti Romain
  * Fichier : class_models.php
  * Version : 1.0
  * Statut : STABLE
  * Note :	This work is licensed under a Creative Commons Attribution 2.5 Generic License http://creativecommons.org/licenses/by/2.5/

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_template.php

---
id: "SystemTemplate.Extensions"
parent_id: "SystemTemplate"
type: class property
line_number: 36
description: |
  Liste des extensions de fichier à analyser.

signatures:
 -
  signature: "SystemTemplate.Extensions"
  return_value: "Array"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_template.php

---
id: "new SystemTemplate"
parent_id: "SystemTemplate"
type: constructor
line_number: 44
description: |
  Cette méthode créée une nouvelle instance de [[SystemTemplate]].

signatures:
 -
  signature: "new SystemTemplate(path [, root [,  header]])"
arguments:
 -
  name: path
  types: [String]
  description: >
    Répertoire du dossier à analyser.

 -
  name: root
  types: [String]
  description: >
    Répertoire racine du site.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_system_template.php