---
id: "JavalyssIconPack"
parent_id: "Core section"
type: class
line_number: 8
description: |
  Cette classe gère le rendu du fichier CSS des icônes.

file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php

---
id: "JavalyssIconPack.Rename"
parent_id: "JavalyssIconPack"
type: class property
line_number: 14
description: |


signatures:
 -
  signature: "JavalyssIconPack.Rename"
  return_value: "Array"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php

---
id: "JavalyssIconPack#Type"
parent_id: "JavalyssIconPack"
type: instance property
line_number: 57
description: |


signatures:
 -
  signature: "JavalyssIconPack#Type"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php

---
id: "JavalyssIconPack#Name"
parent_id: "JavalyssIconPack"
type: instance property
line_number: 61
description: |


signatures:
 -
  signature: "JavalyssIconPack#Name"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php

---
id: "JavalyssIconPack#Link"
parent_id: "JavalyssIconPack"
type: instance property
line_number: 65
description: |


signatures:
 -
  signature: "JavalyssIconPack#Link"
  return_value: "String"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php

---
id: "new JavalyssIconPack"
parent_id: "JavalyssIconPack"
type: constructor
line_number: 76
description: |


signatures:
 -
  signature: "new JavalyssIconPack()"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php

---
id: "JavalyssIconPack.exec"
parent_id: "JavalyssIconPack"
type: class method
line_number: 92
description: |


signatures:
 -
  signature: "JavalyssIconPack.exec()"
  return_value: "void"
file: C:/Users/romak_000/DropBox/mywww/JavalyssLeckye/inc/core/class_javalyss_icon_pack.php